In [1]:
import pandas as pd

df = pd.read_csv("D:\Projects\Project-05 Global Super Store\Data\Global_Superstore.csv", encoding="latin1")

In [2]:
print(df.shape)

df.info()

df.head()

(51290, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [3]:
print(df.shape)
print(df[['City','State']].isnull().sum())

(51290, 24)
City     0
State    0
dtype: int64

In [4]:
df['City'].sample(20)

9002               Bangkok
12376             Toulouse
12948            Singapore
40511              Altoona
28040                 Rome
11928    Palma de Mallorca
40149              Hamburg
16629                 Graz
35137              Jakarta
45992          Santa Clara
19480         Villeurbanne
39339               Kumasi
42748            Frankfurt
26087                 Troy
22626               Lahore
13005        Gómez Palacio
51094                 Kano
9438              Culiacán
38964              Rybinsk
38809             Bagcilar
Name: City, dtype: object

In [5]:
df['State'].sample(20)

8998                  Izmir
20948             Santander
48604            Martinique
36490                Bissau
30971               Lagunes
26758                  Cluj
43794    Kalimantan Selatan
318               Chongqing
629        National Capital
20973              Michigan
21                 Illinois
12669       New South Wales
8750               New York
44610                Vienna
21801         Santo Domingo
49665                 Ouest
37183          Pennsylvania
12783            Washington
1727                  Saida
43796           Maharashtra
Name: State, dtype: object

In [6]:
df['City'] = df['City'].astype(str)
df['State'] = df['State'].astype(str)

city_special = df[df['City'].str.contains(r'[^a-zA-Z0-9\s\-\.\,\(\)]', regex=True, na=False)]
state_special = df[df['State'].str.contains(r'[^a-zA-Z0-9\s\-\.\,\(\)]', regex=True, na=False)]

print("City special records:", len(city_special))
print("State special records:", len(state_special))

City special records: 2671
State special records: 4633

In [7]:
city_special['City'].drop_duplicates().head(100)

24                     Juárez
49                   Paysandú
68              Gómez Palacio
93                   Montréal
107                  Medellín
                ...
4362                  Obregón
4627        Heroica Zitácuaro
4725                   Sumaré
4861             Rondonópolis
4956    São Bernardo do Campo
Name: City, Length: 100, dtype: object

In [8]:
state_special['State'].drop_duplicates().head(100)

49                         Paysandú
66                        Andalusía
81                 Meknès-Tafilalet
105      Provence-Alpes-Côte d'Azur
118                   Midi-Pyrénées
                    ...
12027      Gharb-Chrarda-Béni Hssen
12263                  Södermanland
12732                     Cuscatlán
13737                 San Cristóbal
15981                       Setúbal
Name: State, Length: 100, dtype: object

In [9]:
for col in ['City', 'State', 'Country', 'Product Name']:
    corrupted = df[
        df[col].astype(str)
        .str.contains(r'Ã|Â|�', regex=True, na=False)
    ]

    print(col, len(corrupted))

City 0
State 0
Country 0
Product Name 0

In [10]:
city_special['City'].drop_duplicates().head(50)

24                     Juárez
49                   Paysandú
68              Gómez Palacio
93                   Montréal
107                  Medellín
220                Astrakhan'
267                      Tupã
278                  Camagüey
285                      León
292                  Coyoacán
303                    Ibiúna
373                    Cancún
400       Valparaíso de Goiás
437                  Culiacán
456                    Bogotá
462        Reggio nell'Emilia
485            Ribeirão Preto
500         Antiguo Cuscatlán
502                Guantánamo
546                    Luts'k
555                 São Paulo
607               Santo André
625                  Brasília
643                       Açu
679                    Mérida
715     San José de las Lajas
768                 Paranaguá
783           Sancti Spíritus
851          Lençóis Paulista
860           San Luis Potosí
891                   Torreón
913                     L'viv
922      San Pedro de Macorís
923                    Estelí
931       Consolación del Sur
975                   Copiapó
988                Petrópolis
998                 Araguaína
1068                   Grajaú
1184                   Macapá
1275              São Gonçalo
1464                  Maringá
1517                 Donets'k
1529           Nicolás Romero
1682           Ciego de Ávila
1706          Dnipropetrovs'k
1769               Patrocínio
1793       Balneário Camboriú
1842           José Bonifácio
1859      Santana de Parnaíba
Name: City, dtype: object

In [11]:
for col in ['Row ID', 'Customer ID', 'Order ID', 'Product Name']:
    corrupted2 = df[
        df[col].astype(str)
        .str.contains(r'Ã|Â|�', regex=True, na=False)
    ]

    print(col, len(corrupted2))

Row ID 0
Customer ID 0
Order ID 0
Product Name 0

In [12]:
print(df.shape)

print(df.isnull().sum())

(51290, 24)
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [13]:
for col in df.select_dtypes(include='object').columns:
    comma_count = df[col].astype(str).str.contains(',', regex=False).sum()
    if comma_count > 0:
        print(col, ":", comma_count)

Product Name : 43517

In [14]:
for col in df.select_dtypes(include='object').columns:
    semicolon_count = df[col].astype(str).str.contains(';', regex=False).sum()
    if semicolon_count > 0:
        print(col, ":", semicolon_count)

Product Name : 6

In [15]:
df[
    df['Product Name']
    .astype(str)
    .str.contains(';', regex=False)
][['Product Name']]

                                            Product Name
4946   Imation Secure+ Hardware Encrypted USB 2.0 Fla...
6562   Imation Secure+ Hardware Encrypted USB 2.0 Fla...
7595   Imation Secure+ Hardware Encrypted USB 2.0 Fla...
8140   Imation Secure+ Hardware Encrypted USB 2.0 Fla...
10901  Imation Secure+ Hardware Encrypted USB 2.0 Fla...
16340  Imation Secure+ Hardware Encrypted USB 2.0 Fla...

In [16]:
df[
    df['Product Name']
    .astype(str)
    .str.contains('"', regex=False)
][['Product Name']].head(20)

                                           Product Name
121   HP Designjet T520 Inkjet Large Format Printer ...
126   Chromcraft 48" x 96" Racetrack Double Pedestal...
179   HP Designjet T520 Inkjet Large Format Printer ...
331             Bevis Round Bullnose 29" High Table Top
961            Tenex Chairmat w/ Average Lip, 45" x 53"
1133  Office Impressions End Table, 20-1/2"H x 24"W ...
1271  Chromcraft Bull-Nose Wood 48" x 96" Rectangula...
1743            Bevis Round Bullnose 29" High Table Top
1919  Office Impressions End Table, 20-1/2"H x 24"W ...
2076               Iceberg OfficeWorks 42" Round Tables
2791  Tenex Traditional Chairmats for Medium Pile Ca...
3007  Office Impressions End Table, 20-1/2"H x 24"W ...
3024  Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...
3103               Iceberg OfficeWorks 42" Round Tables
3765            Bevis Round Bullnose 29" High Table Top
3842  Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...
3908           Tenex Chairmat w/ Average Lip, 45" x 53"
4087  Barricks 18" x 48" Non-Folding Utility Table w...
4284  Howard Miller 13-3/4" Diameter Brushed Chrome ...
4677  Rush Hierlooms Collection 1" Thick Stackable B...

In [17]:
df.drop(columns=['Postal Code'], inplace=True)

In [18]:
for col in df.select_dtypes(include='object').columns:
    count = df[col].astype(str).str.contains('\n', regex=False).sum()
    if count > 0:
        print(col, count)

In [19]:
for col in df.select_dtypes(include='object').columns:
    count = df[col].astype(str).str.contains('\r', regex=False).sum()
    if count > 0:
        print(col, count)

In [20]:
for col in df.select_dtypes(include='object').columns:
    count = df[col].astype(str).str.contains('\t', regex=False).sum()
    if count > 0:
        print(col, count)

In [21]:
for col in df.select_dtypes(include='object').columns:
    print(
        col,
        df[col].astype(str).str.len().max()
    )

Order ID 15
Order Date 10
Ship Date 10
Ship Mode 14
Customer ID 8
Customer Name 22
Segment 11
City 35
State 36
Country 32
Market 6
Region 14
Product ID 16
Category 15
Sub-Category 11
Product Name 127
Order Priority 8

In [22]:
df['Product Name'] = (
    df['Product Name']
    .astype(str)
    .str.replace('"', '', regex=False)
)

df['Customer Name'] = (
    df['Customer Name']
    .astype(str)
    .str.replace('"', '', regex=False)
)

In [23]:
df.iloc[1680:1685]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1680,23250,IN-2011-62037,11-11-2011,14-11-2011,First Class,TP-21130,Theone Pippenger,Consumer,Ho Chi Minh City,Ho Chí Minh City,...,OFF-ST-10001638,Office Supplies,Storage,"Tenex File Cart, Single Width",893.8104,8,0.17,129.1704,150.07,Critical
1681,33412,CA-2012-164882,31-10-2012,31-10-2012,Same Day,SG-20080,Sandra Glassco,Consumer,Redlands,California,...,FUR-BO-10002213,Furniture,Bookcases,DMI Eclipse Executive Suite Bookcases,425.8330,1,0.15,20.0392,150.07,Critical
1682,7807,MX-2012-135174,22-10-2012,26-10-2012,Standard Class,SD-20485,Shirley Daniels,Home Office,Ciego de Ávila,Ciego de Ávila,...,FUR-TA-10000805,Furniture,Tables,"Bevis Wood Table, Adjustable Height",1428.8000,4,0.00,628.6400,150.07,High
1683,18090,ES-2012-2212320,24-08-2012,29-08-2012,Standard Class,SP-20920,Susan Pistek,Consumer,Bochum,North Rhine-Westphalia,...,TEC-PH-10002035,Technology,Phones,"Samsung Smart Phone, Cordless",1917.0000,3,0.00,134.1900,150.05,High
1684,50086,RS-2012-7220,17-12-2012,19-12-2012,Second Class,GW-4605,Giulietta Weimer,Consumer,Arkhangelsk,Arkhangel'sk,...,TEC-EPS-10001651,Technology,Machines,"Epson Phone, White",635.0400,8,0.00,241.2000,150.05,Critical

In [24]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Ship Date'] = pd.to_datetime(df['Ship Date'])

C:\Users\Hp\AppData\Local\Temp\ipykernel_15080\187968752.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order Date'] = pd.to_datetime(df['Order Date'])
C:\Users\Hp\AppData\Local\Temp\ipykernel_15080\187968752.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [25]:
for col in df.select_dtypes(include='object').columns:
    bad = (
        df[col]
        .astype(str)
        .str.contains(r'Â|Ã|�', regex=True, na=False)
        .sum()
    )

    if bad > 0:
        print(col, bad)

In [26]:
for col in df.select_dtypes(include='object').columns:

    newline = df[col].astype(str).str.contains('\n', regex=False).sum()
    carriage = df[col].astype(str).str.contains('\r', regex=False).sum()
    tab = df[col].astype(str).str.contains('\t', regex=False).sum()

    if newline > 0 or carriage > 0 or tab > 0:
        print(col)
        print("Newlines:", newline)
        print("Carriage Returns:", carriage)
        print("Tabs:", tab)
        print("-"*30)

In [27]:
for col in df.select_dtypes(include='object').columns:

    comma = df[col].astype(str).str.contains(',', regex=False).sum()
    quote = df[col].astype(str).str.contains('"', regex=False).sum()
    semicolon = df[col].astype(str).str.contains(';', regex=False).sum()

    print(
        col,
        "| Comma:", comma,
        "| Quotes:", quote,
        "| Semicolon:", semicolon
    )

Order ID | Comma: 0 | Quotes: 0 | Semicolon: 0
Ship Mode | Comma: 0 | Quotes: 0 | Semicolon: 0
Customer ID | Comma: 0 | Quotes: 0 | Semicolon: 0
Customer Name | Comma: 0 | Quotes: 0 | Semicolon: 0
Segment | Comma: 0 | Quotes: 0 | Semicolon: 0
City | Comma: 0 | Quotes: 0 | Semicolon: 0
State | Comma: 0 | Quotes: 0 | Semicolon: 0
Country | Comma: 0 | Quotes: 0 | Semicolon: 0
Market | Comma: 0 | Quotes: 0 | Semicolon: 0
Region | Comma: 0 | Quotes: 0 | Semicolon: 0
Product ID | Comma: 0 | Quotes: 0 | Semicolon: 0
Category | Comma: 0 | Quotes: 0 | Semicolon: 0
Sub-Category | Comma: 0 | Quotes: 0 | Semicolon: 0
Product Name | Comma: 43517 | Quotes: 0 | Semicolon: 6
Order Priority | Comma: 0 | Quotes: 0 | Semicolon: 0

In [28]:
import csv

df.to_csv("D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned.csv",index=False,encoding="utf-8")

In [29]:
with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned.csv",
    "r",
    encoding="utf-8"
) as f:

    for i in range(5):
        print(f.readline())

Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority

32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wireless Headset System,2309.65,7,0.0,762.1845,933.57,Critical

26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.765,923.63,Critical

25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.971,915.49,Medium

13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.16,Medium

In [30]:
import csv

with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned.csv",
    encoding="utf-8"
) as f:

    row_count = sum(1 for row in csv.reader(f))

print("Rows in CSV:", row_count)

Rows in CSV: 51291

In [31]:
import csv

df.to_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    index=False,
    encoding="utf-8",
    quoting=csv.QUOTE_ALL
)

PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\Project-05 Global Super Store\\Data\\Global_Superstore_Cleaned_Quoted.csv'

In [ ]:
with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    "r",
    encoding="utf-8"
) as f:

    for i in range(5):
        print(f.readline())

In [ ]:
import csv

with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    encoding="utf-8"
) as f:
    print("Total Rows:", sum(1 for row in csv.reader(f)))

In [ ]:
import csv

with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    encoding="utf-8"
) as f:
    print(sum(1 for row in csv.reader(f)))

In [ ]:
row = df.iloc[1679]

for col in df.columns:
    print(col, ":", repr(row[col]))

In [ ]:
row = df.iloc[1680]

for col in df.columns:
    print(col, ":", repr(row[col]))

In [ ]:
for col in df.select_dtypes(include='object').columns:

    count = df[col].astype(str).str.contains("'", regex=False).sum()

    if count > 0:
        print(col, count)

In [ ]:
for col in df.select_dtypes(include='object').columns:

    bad = df[
        df[col].astype(str).str.contains("'", regex=False)
    ]

    if len(bad) > 0:
        print("\n", col)
        print(bad[[col]].drop_duplicates().head(20))

In [ ]:
df.iloc[1675:1685]

In [ ]:
df.iloc[1675:1685][
[
'City',
'State',
'Country',
'Product Name'
]
]

In [ ]:
for col in df.columns:
    max_len = df[col].astype(str).str.len().max()
    print(col, ":", max_len)

In [ ]:
for col in df.select_dtypes(include='object').columns:

    long_values = df[
        df[col].astype(str).str.len() > 100
    ][[col]]

    if len(long_values) > 0:
        print("\n", col)
        print(long_values.head(20))

In [ ]:
import csv

with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    "r",
    encoding="utf-8"
) as f:

    reader = csv.reader(f)

    bad_rows = []

    for i, row in enumerate(reader):

        if len(row) != 23:      # expected columns
            bad_rows.append((i, len(row)))

    print("Bad rows:", len(bad_rows))

    print(bad_rows[:20])

In [ ]:
import csv

with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv",
    "r",
    encoding="utf-8"
) as f:

    reader = csv.reader(f)

    for i, row in enumerate(reader):

        if len(row) != 23:
            print("Row", i)
            print(row)
            break

In [ ]:
len(row) != 23

In [ ]:
import csv

file = r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Cleaned_Quoted.csv"

bad_rows = []

with open(file, "r", encoding="utf-8") as f:
    reader = csv.reader(f)

    for i, row in enumerate(reader):

        if len(row) != 24:
            bad_rows.append((i, len(row)))

print("Bad rows:", len(bad_rows))

print(bad_rows[:20])

In [32]:
df["Order Date"] = pd.to_datetime(df["Order Date"]).dt.strftime("%Y-%m-%d")
df["Ship Date"] = pd.to_datetime(df["Ship Date"]).dt.strftime("%Y-%m-%d")

In [34]:
print(df[["Order Date", "Ship Date"]].head())
print(df.dtypes)

   Order Date   Ship Date
0  2012-07-31  2012-07-31
1  2013-02-05  2013-02-07
2  2013-10-17  2013-10-18
3  2013-01-28  2013-01-30
4  2013-11-05  2013-11-06
Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
City               object
State              object
Country            object
Market             object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
Shipping Cost     float64
Order Priority     object
dtype: object

In [35]:
df.to_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv",
    index=False,
    encoding="utf-8"
)

In [36]:
with open(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv",
    "r",
    encoding="utf-8"
) as f:
    for i in range(5):
        print(f.readline())

Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority

32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wireless Headset System,2309.65,7,0.0,762.1845,933.57,Critical

26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.765,923.63,Critical

25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.971,915.49,Medium

13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.16,Medium

In [37]:
print(df["Order Date"].head(10))

0    2012-07-31
1    2013-02-05
2    2013-10-17
3    2013-01-28
4    2013-11-05
5    2013-06-28
6    2011-11-07
7    2012-04-14
8    2014-10-14
9    2012-01-28
Name: Order Date, dtype: object

In [38]:
df.to_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv",
    index=False,
    encoding="utf-8"
)

In [39]:
bad_products = df[
    df["Product Name"].astype(str).str.contains("Â", regex=False, na=False)
]

print("Bad Product Names:", len(bad_products))

bad_products[["Product Name"]].drop_duplicates().head(50)

Bad Product Names: 0

Empty DataFrame
Columns: [Product Name]
Index: []

In [40]:
df["Product Name"] = (
    df["Product Name"]
    .str.replace("Â“", '"', regex=False)
    .str.replace("Â”", '"', regex=False)
    .str.replace("Â", "", regex=False)
)

In [41]:
print(
    df["Product Name"]
      .astype(str)
      .str.contains("Â", regex=False)
      .sum()
)

0

In [42]:
for col in df.select_dtypes(include="object").columns:
    count = df[col].astype(str).str.contains("Â", regex=False).sum()

    if count > 0:
        print(col, count)

In [43]:
df.to_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv",
    index=False,
    encoding="utf-8"
)

In [44]:
import pandas as pd

df = pd.read_csv("D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv", encoding="latin1")

In [45]:
bad_products = df[
    df["Product Name"].astype(str).str.contains("Â", regex=False, na=False)
]

print("Bad Product Names:", len(bad_products))

bad_products[["Product Name"]].drop_duplicates().head(50)

Bad Product Names: 266

                                            Product Name
165                  LogitechÂ P710e Mobile Speakerphone
209           Polycom SoundStation2 EX ConferenceÂ phone
212    Hon 2090 ÂPillow SoftÂ Series Mid Back Swive...
337    LogitechÂ Z-906 Speaker sys - home theater - 5...
428             ClearOne CHATAttach 160 -Â speaker phone
837    LogitechÂ VX Revolution Cordless Laser Mouse f...
1268          Jabra Supreme Plus Driver EditionÂ Headset
1277                     MaxellÂ iVDR EX 500GB Cartridge
1820      Imation Bio 8GB USBÂ Flash Drive ImationÂ Corp
2003   Bretford ÂJust In TimeÂ Height-Adjustable Mu...
2220      Imation Bio 2GB USBÂ Flash Drive ImationÂ Corp
2257          Polycom VoiceStation 500 ConferenceÂ phone
2787                   LogitechÂ Gaming G510s - Keyboard
3216   NETGEAR AC1750 Dual Band GigabitÂ Smart WiFi R...
3719     Konftel 250 ConferenceÂ phoneÂ - Charcoal black
3740   ClearOne Communications CHAT 70 OCÂ Speaker Phone
3935                    Toshiba IPT2010-SD IPÂ Telephone
4223   Plantronics CS 50-USB -Â headsetÂ - Convertibl...
4946   ImationÂ Secure+ Hardware Encrypted USB 2.0Â F...
5182            Panasonic BusinessÂ TelephonesÂ KX-T7736
5188   Blue Parrot B250XT Professional Grade Wireless...
5338     Cisco IPÂ PhoneÂ 7961G VoIPÂ phoneÂ - Dark gray
5948           Jabra BIZ 2300 Duo QD Duo CordedÂ Headset
6062   Logitech Mobile Speakerphone P710e -Â speaker ...
6462   ImationÂ 16GB Mini TravelDrive USB 2.0Â Flash ...
6901   Plantronics CordlessÂ Phone HeadsetÂ with In-l...
6908                    LogitechÂ Illuminated - Keyboard
6985   ImationÂ 8gb Micro Traveldrive Usb 2.0Â Flash ...
7031     Plantronics Encore H101 Dual EarpiecesÂ Headset
7206   LogitechÂ Wireless Boombox Speaker - portable ...
7380   Xblue XB-1670-86 X16 SmallÂ Office TelephoneÂ ...
8224   ImationÂ 8GB Mini TravelDrive USB 2.0Â Flash D...
8619                        MaxellÂ LTO Ultrium - 800 GB
9416         KeyTronicÂ 6101 Series -Â KeyboardÂ - Black
10016                   Pyle PRT45 Retro HomeÂ Telephone
10894            LogitechÂ MX Performance Wireless Mouse
12708  ImationÂ SecureÂ DriveÂ + Hardware Encrypted U...
13436           Classic Ivory AntiqueÂ TelephoneÂ ZL1810
15780             ImationÂ Clip USBÂ flash driveÂ - 8 GB
20134           KeyTronicÂ E03601U1 -Â KeyboardÂ - Beige
20486  ImationÂ 32GB Pocket Pro USB 3.0Â Flash DriveÂ...
21435                   Jensen SMPS-640 -Â speaker phone
21518  Standard Line ÂWhile You Were OutÂ Hardbound...
21651  Logitech B530 USBÂ HeadsetÂ -Â headsetÂ - Full...
22245  Ampad Phone Message Book, Recycled, 400 Messag...
25917  Adams Phone Message Book, 200 Message Capacity...
26050  LogitechÂ LS21 Speaker System - PC Multimedia ...
27656  Wilson Jones ÂSnapÂ Scratch Pad Binder Tool ...
30588  Adams Phone Message Book, Professional, 400 Me...
32299               ImationÂ 30456 USBÂ Flash DriveÂ 8GB

In [46]:
df["Product Name"] = (
    df["Product Name"]
    .astype(str)
    .str.replace("Â“", '"', regex=False)
    .str.replace("Â”", '"', regex=False)
    .str.replace("Â‘", "'", regex=False)
    .str.replace("Â’", "'", regex=False)
    .str.replace("Â", "", regex=False)
)

In [47]:
df[
    df["Product Name"].astype(str).str.contains("Â", regex=False, na=False)
][["Product Name"]]

Empty DataFrame
Columns: [Product Name]
Index: []

In [48]:
for pattern in ["Â", "Ã", "â"]:
    count = df["Product Name"].astype(str).str.contains(
        pattern,
        regex=False,
        na=False
    ).sum()

    print(pattern, ":", count)

Â : 0
Ã : 10
â : 0

In [49]:
bad = df[
    df["Product Name"].astype(str).str.contains("Ã", regex=False, na=False)
]

print(len(bad))
bad[["Product Name"]].drop_duplicates()

10

                                      Product Name
20253        Southworth 100% RÃ©sumÃ© Paper, 24lb.
40976  Eldon ImÃ ge Series Desk Accessories, Clear

In [50]:
bad = df[
    df["Product Name"].astype(str).str.contains("Ã", regex=False, na=False)
]["Product Name"]

for item in bad.unique():
    print(item)
    print("-"*100)

Southworth 100% RÃ©sumÃ© Paper, 24lb.
----------------------------------------------------------------------------------------------------
Eldon ImÃ ge Series Desk Accessories, Clear
----------------------------------------------------------------------------------------------------

In [51]:
df[
    df["Product Name"].str.contains("Southworth|Eldon", na=False)
][["Product Name"]].drop_duplicates()

                                            Product Name
379                        Eldon File Cart, Single Width
850                                  Eldon Lockers, Blue
1046                               Eldon File Cart, Blue
1076                           Eldon Lockers, Industrial
1078                           Eldon Lockers, Wire Frame
...                                                  ...
41488      Eldon Image Series Desk Accessories, Burgundy
44983          Eldon Image Series Black Desk Accessories
45251    Southworth 25% Cotton Granite Paper & Envelopes
45711                      Eldon Pizzaz Desk Accessories
48536  Eldon Regeneration Recycled Desk Accessories, ...

[104 rows x 1 columns]

In [52]:
df["Product Name"] = df["Product Name"].replace({
    "Southworth 100% RÃ©sumÃ© Paper, 24lb.": "Southworth 100% Résumé Paper, 24lb.",
    "Eldon ImÃ ge Series Desk Accessories, Clear": "Eldon Image Series Desk Accessories, Clear"
})

In [53]:
for pattern in ["Â", "Ã", "â"]:
    count = (
        df["Product Name"]
        .astype(str)
        .str.contains(pattern, regex=False, na=False)
        .sum()
    )
    print(pattern, ":", count)

Â : 0
Ã : 3
â : 0

In [54]:
df[
    df["Product Name"].astype(str).str.contains("Ã", regex=False, na=False)
][["Product Name"]].drop_duplicates()

                                      Product Name
40976  Eldon ImÃ ge Series Desk Accessories, Clear

In [55]:
bad = df[
    df["Product Name"].astype(str).str.contains("Ã", regex=False, na=False)
]["Product Name"]

for x in bad.unique():
    print(x)
    print("-"*100)

Eldon ImÃ ge Series Desk Accessories, Clear
----------------------------------------------------------------------------------------------------

In [56]:
bad = df[
    df["Product Name"].astype(str).str.contains("Ã", regex=False, na=False)
]

print("Rows:", len(bad))
bad[["Product Name"]]

Rows: 3

                                      Product Name
40976  Eldon ImÃ ge Series Desk Accessories, Clear
46247  Eldon ImÃ ge Series Desk Accessories, Clear
51242  Eldon ImÃ ge Series Desk Accessories, Clear

In [57]:
def fix_encoding(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except:
        return text

df["Product Name"] = df["Product Name"].astype(str).apply(fix_encoding)

In [58]:
for pattern in ["Â", "Ã", "â"]:
    print(
        pattern,
        df["Product Name"].astype(str)
        .str.contains(pattern, regex=False, na=False)
        .sum()
    )

Â 0
Ã 0
â 0

In [60]:
for i in range(1646, 1651):
    print("\nRow:", i)
    print(repr(df.loc[i, "Product Name"]))

Row: 1646
'Polycom VVX 310 VoIP phone'

Row: 1647
'SAFCO Executive Leather Armchair, Set of Two'

Row: 1648
'Hamilton Beach Stove, White'

Row: 1649
'Canon Copy Machine, Color'

Row: 1650
'Hewlett Fax Machine, High-Speed'

In [61]:
df.iloc[1646:1651][
    ["Customer Name","City","State","Country","Product Name"]
]

,Customer Name,City,State,Country,Product Name
1646,Michael Nguyen,El Paso,Texas,United States,Polycom VVX 310 VoIP phone
1647,Thomas Seio,Sydney,New South Wales,Australia,"SAFCO Executive Leather Armchair, Set of Two"
1648,Neola Schneider,Kano,Kano,Nigeria,"Hamilton Beach Stove, White"
1649,Tonja Turnell,Bekasi,Jawa Barat,Indonesia,"Canon Copy Machine, Color"
1650,Sandra Flanagan,Changzhou,Jiangsu,China,"Hewlett Fax Machine, High-Speed"

In [62]:
for i in range(1646, 1651):
    text = str(df.loc[i, "Product Name"])

    bad_chars = [c for c in text if ord(c) > 127]

    if bad_chars:
        print(i, bad_chars)

In [63]:
row = df.iloc[1648]

for col in df.columns:
    print(col, ":", repr(row[col]))

Row ID : np.int64(43505)
Order ID : 'NI-2013-2220'
Order Date : '3/1/2013'
Ship Date : '3/1/2013'
Ship Mode : 'Same Day'
Customer ID : 'NS-8505'
Customer Name : 'Neola Schneider'
Segment : 'Consumer'
City : 'Kano'
State : 'Kano'
Country : 'Nigeria'
Market : 'Africa'
Region : 'Africa'
Product ID : 'OFF-HAM-10003040'
Category : 'Office Supplies'
Sub-Category : 'Appliances'
Product Name : 'Hamilton Beach Stove, White'
Sales : np.float64(648.576)
Quantity : np.int64(4)
Discount : np.float64(0.7)
Profit : np.float64(-886.464)
Shipping Cost : np.float64(151.84)
Order Priority : 'High'

In [64]:
for col in df.select_dtypes(include="object").columns:

    count = df[col].astype(str).apply(
        lambda x: any(ord(c) > 127 for c in x)
    ).sum()

    print(col, ":", count)

Order ID : 0
Order Date : 0
Ship Date : 0
Ship Mode : 0
Customer ID : 0
Customer Name : 416
Segment : 0
City : 2349
State : 4255
Country : 0
Market : 0
Region : 0
Product ID : 0
Category : 0
Sub-Category : 0
Product Name : 276
Order Priority : 0

In [65]:
for pattern in ["Â", "Ã", "â"]:
    print("\nPattern:", pattern)

    for col in df.select_dtypes(include="object").columns:
        count = (
            df[col]
            .astype(str)
            .str.contains(pattern, regex=False, na=False)
            .sum()
        )

        if count > 0:
            print(col, ":", count)

Pattern: Â
City : 2
State : 6

Pattern: Ã
Customer Name : 416
City : 2347
State : 4249

Pattern: â

In [66]:
for pattern in ["Â", "Ã", "â"]:
    print("\n==============================")
    print("PATTERN:", repr(pattern))
    print("==============================")

    for col in df.select_dtypes(include="object").columns:
        bad = df[
            df[col].astype(str).str.contains(
                pattern,
                regex=False,
                na=False
            )
        ][col].drop_duplicates()

        if len(bad) > 0:
            print(f"\n{col} — {len(bad)} unique values")
            print(bad.head(10).tolist())

==============================
PATTERN: 'Â'
==============================

City — 1 unique values
['CoxÂ\x92s B?z?r']

State — 2 unique values
['Â\x8aiauliai', 'Â\x8eilina']

==============================
PATTERN: 'Ã'
==============================

Customer Name — 6 unique values
['Resi PÃ¶lking', 'Neil FranzÃ¶sisch', 'Peter BÃ¼hler', 'Barry FranzÃ¶sisch', 'Roy FranzÃ¶sisch', 'Anna HÃ¤berlin']

City — 197 unique values
['JuÃ¡rez', 'PaysandÃº', 'GÃ³mez Palacio', 'MontrÃ©al', 'MedellÃ\xadn', 'TupÃ£', 'CamagÃ¼ey', 'LeÃ³n', 'CoyoacÃ¡n', 'IbiÃºna']

State — 88 unique values
['PaysandÃº', 'AndalusÃ\xada', 'MeknÃ¨s-Tafilalet', "Provence-Alpes-CÃ´te d'Azur", 'Midi-PyrÃ©nÃ©es', 'SÃ£o Paulo', 'MichoacÃ¡n', 'Ho ChÃ\xad Minh City', 'CamagÃ¼ey', 'LeÃ³n']

==============================
PATTERN: 'â'
==============================

In [67]:
for pattern in ["Â", "Ã", "â"]:
    print(
        repr(pattern),
        [hex(ord(c)) for c in pattern]
    )

'Â' ['0xc2']
'Ã' ['0xc3']
'â' ['0xe2']

In [68]:
for col in ["Customer Name","City","State","Product Name"]:
    bad = df[df[col].astype(str).str.contains("Ã", na=False)]

    print("\n", col)
    print("Rows:", len(bad))

 Customer Name
Rows: 416

 City
Rows: 2347

 State
Rows: 4249

 Product Name
Rows: 0

In [69]:
def fix_mojibake(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except:
        return text

for col in ["Customer Name","City","State","Product Name"]:
    df[col] = df[col].astype(str).apply(fix_mojibake)

In [70]:
for col in ["Customer Name","City","State","Product Name"]:
    count = df[col].astype(str).str.contains("Ã", na=False).sum()
    print(col, count)

Customer Name 0
City 0
State 0
Product Name 0

In [71]:
df[df["City"].str.contains("Ju", na=False)][["City"]].drop_duplicates()

                         City
24                     Juárez
517    San Juan de la Maguana
2124                 San Juan
2782             Juiz de Fora
4722                     Juba
7360                  Jundiaí
7692         San Juan del Río
11230               San Justo
11319                  Jurema
17626                Juazeiro
18000                 Juliaca
18901   San Salvador de Jujuy
26277                   Junín
50664                 Jupiter

In [73]:
import pandas as pd

test = pd.read_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv"
)

print(test.shape)

(51290, 19)

In [72]:
df.to_csv(
    r"D:\Projects\Project-05 Global Super Store\Data\Global_Superstore_Final.csv",
    index=False,
    encoding="utf-8"
)

In [74]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Puwal@2002")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/global_superstore_analysis"
)

with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [77]:
df.head(100).to_sql(
    "test_import",
    engine,
    if_exists="replace",
    index=False
)

print("100 rows imported successfully")

100 rows imported successfully

In [78]:
import pandas as pd

pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM test_import",
    engine
)

   cnt
0  100

In [83]:
df.to_sql(
    "global_superstore",
    engine,
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

51290

In [84]:
pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM global_superstore",
    engine
)

     cnt
0  51290

In [85]:
print(df.shape)

(51290, 23)

In [86]:
pd.read_sql(
    """
    SELECT
        COUNT(*) AS Total_Rows,
        COUNT(DISTINCT `Order ID`) AS Unique_Orders,
        SUM(Sales) AS Total_Sales
    FROM global_superstore
    """,
    engine
)

   Total_Rows  Unique_Orders   Total_Sales
0       51290          25035  1.264250e+07